export const SET_PLAYING = "SET_PLAYING";
export const SET_LISTENING = "SET_LISTENING";
export const ADD_LOADED_SONG = "ADD_LOADED_SONG";
export const SET_LOADING_SONG = "SET_LOADING_SONG";
export const REMOVE_LOADED_SONG = "REMOVE_LOADED_SONG";
export const SHOW_OPTIONS_SHEET = "SHOW_OPTIONS_SHEET";
export const SET_SONG_FOR_DETAILS = "SET_SONG_FOR_DETAILS";